export const SET_TAB = 'SET_TAB';
export type SET_TAB = typeof SET_TAB;

export const SET_STATE = 'SET_STATE';
export type SET_STATE = typeof SET_STATE;

export const ADD_PHOTOS = 'ADD_PHOTOS';
export type ADD_PHOTOS = typeof ADD_PHOTOS;

export const OPEN_PHOTO_BROWSE = 'OPEN_PHOTO_BROWSE';
export type OPEN_PHOTO_BROWSE = typeof OPEN_PHOTO_BROWSE;

export const CLEAR_PHOTO_BROWSE = 'CLEAR_PHOTO_BROWSE';
export type CLEAR_PHOTO_BROWSE = typeof CLEAR_PHOTO_BROWSE;

export const PREV_PHOTO_BROWSE = 'PREV_PHOTO_BROWSE';
export type PREV_PHOTO_BROWSE = typeof PREV_PHOTO_BROWSE;

export const NEXT_PHOTO_BROWSE = 'NEXT_PHOTO_BROWSE';
export type NEXT_PHOTO_BROWSE = typeof NEXT_PHOTO_BROWSE;

export const TOGGLE_PHOTO_SELECT = 'TOGGLE_PHOTO_SELECT';
export type TOGGLE_PHOTO_SELECT = typeof TOGGLE_PHOTO_SELECT;

export const CLEAR_PHOTO_SELECT = 'CLEAR_PHOTO_SELECT';
export type CLEAR_PHOTO_SELECT = typeof CLEAR_PHOTO_SELECT;

export const SET_UPLOAD_PROGRESS = 'SET_UPLOAD_PROGRESS';
export type SET_UPLOAD_PROGRESS = typeof SET_UPLOAD_PROGRESS;
